travis:
  secure:
    BINSTAR_TOKEN: ZRyl98JvBn6JudKSoZXU9IeEC2HP0uiuZbnKlri02ZpQtG3FtAUEBSoNxwAqUTtboom6zSp66HxqYYJuhKvNnJquFmXUl0qTc1/IJ8tF5qWq+0Aur8YoJIqrP4i6gi0OkFicX3u+y+D95xvvuNKSXPoYUl4bMvqgENLC4oST0v4urOGBTuEnVe2ulEviCrBR+QgVYGOZaHYGtHBeFvp+xE3rbHppOwLFevbKR3AwsMQBY8w8uc8pr0kcf+bNjW6HpbQ5y/g9XwOC0jI8PXIlm7e6othcnRuSE/S2eyMFIjayHPCkxnpIfZKelJdBsADWRBDA970AdDQqksSpoBpBCRC9t+9Aiq4Qd3yEqak2xaUMwCVtqnoZrTJjqUcFFSDzuRyRt3G0oXXvV7+oAN9oEe600mEXIOmBv2Zp9/OEHL28v+tijDN/vuHPHIgQSaq6Duc/WCMJIUWpmRVowO3+kHamL8YJ/boLxcydP1yL6tLq+oayqOLeGWwwCEc3szsORaUgzi1pNyPIIiJL4OZaxMDUOszvkulMAqP54lH/B39QGwJdj/McFibSl5BYClPX6aslPjBD0cfBOm6Y5CxDftYM1rZxuLQJ7TPb/AD9eWx7AlejS/aIfefX9+W9N/W1Lv+HPn45VRa1GTz3Y3XuY2pNfwgUu5iM5R2nJoree7c=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
